name: Prepare Artifacts
description: "Prepares the binary artifacts for uploading"
inputs:
  os:
    description: "the os name for the artifact, as in: linux"
    default: "default"
  arch:
    description: "the artifact architecture, as in x64"
runs:
  using: "composite"
  steps:
    - name: Prepare Artifacts
      shell: bash
      run: |
        ARTIFACT_NAME="git-llm-utils-${{ inputs.os }}-${{ inputs.arch }}"
        ARTIFACT_NAME=$(tr '[:upper:]' '[:lower:]' <<< "$ARTIFACT_NAME")
        cd dist
        $(which zip && echo ' -9 -r' || echo '7z a') ${ARTIFACT_NAME}.zip .
        echo "ARTIFACT=dist/${ARTIFACT_NAME}.zip" >> $GITHUB_ENV
        echo "ARTIFACT_NAME=${ARTIFACT_NAME}.zip" >> $GITHUB_ENV
